
export const dummyData = [
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    },
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    },
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    },
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    }
    ,
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    }
    ,
    {
        countryName:'Cameroon',
        threatenedSpecies:77,
        protectedSpecies:1,
        nonProtectedSpecies:76,
        knownThreats:42,
        hotspotHabitats:27
    }
    
    
]